import Head from 'next/head'
// import Image from 'next/image'
import { Manrope } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Flex, VStack, Text, Image, Circle } from '@chakra-ui/react'
import {useState, useEffect } from 'react'

const manrope = Manrope({weight:'800', subsets: ['latin'] })

export default function Home() {
  const [id, setId] = useState('');
  const [advice, setAdvice] = useState('');

  function roll(){
    fetch('https://api.adviceslip.com/advice')
    .then((res)=>res.json())
    .then((data)=>{
      setId(data.slip.id)
      setAdvice(data.slip.advice)
      console.log(data.slip.id)
    })
    
  }
  useEffect(()=>{
    roll()
  }, [])
  return (
    <>
      <Head>
        <title>Advice Generator App</title>
        <meta name="description" content="Generated by Nida Nido" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-3232.png" />
      </Head>
      <main className={manrope.className}>
        <Flex flexFlow="column nowrap" justifyContent="center" alignItems="center" w="100vw" h="100vh" bg="brand.darkBlue">
          <VStack w="90%" maxW="500px" h="fit-content"  borderRadius="15px" bg="brand.darkGreyBlue" 
          p={{base:"30px", sm:"50px"}} pb={{base:0, sm:0}} spacing="40px">
            <Text color="brand.neonGreen">ADVICE #{id}</Text>
            <Text textAlign='center' fontSize="28px" color="brand.lightCyan">"{advice}"</Text>
            <Image src="/images/pattern-divider-desktop.svg" />
            <Circle as="button" bg="brand.neonGreen" size="60px" onClick={()=>roll()} mb="-30px !important"
            _hover={{boxShadow:"0 0 30px 0 hsl(193, 38%, 86%)"}}
            >
                <Image src="/images/icon-dice.svg"  />  
            </Circle>    
            
          </VStack>
        </Flex>
      </main>
    </>
  )
}
